site_name: RustDocs - 个人 Rust 学习文档
site_description: 关于 RustDocs - 个人 Rust 学习的说明文档
site_author: 程思翔
site_url: https://chengsx21.github.io/Rust-Docs/
copyright: Copyright © 2024 [Nullptr]

repo_name: 'chengsx21/Rust-Docs'
repo_url: 'https://github.com/chengsx21/Rust-Docs'

theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: images/logo.svg
  favicon: images/logo.svg
  language: zh

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - 概述: index.md
  - 学习笔记: 
    - 从 Cargo 说到基本类型: doc-1.md
    - 所有权与进阶类型: doc-2.md
    - 结构体与模式匹配: doc-3.md
    - 泛型与特征: doc-4.md
