site_name: GifExplorer - 图片检索系统
site_description: 关于 GifExplorer - 图片检索系统的说明文档
site_author: 陈鑫圣 程思翔 李羽飞 刘竞暄 卢天彧
site_url: https://chengsx21.github.io/Rust-Docs/
copyright: Copyright © 2023 [Nullptr]

repo_name: 'chengsx21/GifExplorer-docs'
repo_url: 'https://github.com/chengsx21/Rust-Docs'

theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: images/logo.svg
  favicon: images/logo.svg
  language: zh

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - 概述: index.md
  - 需求及分析: 
    - 需求分析: structure.md
    - 需求实现: implement.md
    - 检索召回率分析: recall.md
  - 模块设计:
    - 数据库设计: modules/database.md
    - 接口设计: 
      - 通用接口: modules/api.md
      - 搜索接口: modules/search-api.md
    - 各模块主要设计:
      - 爬虫: modules/spider.md
      - 检索: modules/search.md
      - 前端: modules/frontend.md
      - 后端: modules/django.md
